services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: fina
      POSTGRES_PASSWORD: fina
      POSTGRES_DB: fina
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
